from typing import List, Optional
from models.review import Issue, IssueType, Severity, ReviewResponse


class GitHubCommenter:
    def __init__(self, github_client):
        self.github_client = github_client

    def format_review_comment(self, review: ReviewResponse) -> str:
        lines = [
            "## 🤖 AI Code Review Results",
            "",
            f"**File:** `{review.file_path}`",
            f"**Overall Risk:** {review.summary.overall_risk.upper()}",
            f"**Total Issues:** {review.summary.total_issues}",
            "",
            "### Summary by Severity",
            "| Severity | Count |",
            "|----------|-------|",
        ]

        severity_order = ["critical", "high", "medium", "low", "info"]
        for sev in severity_order:
            count = review.summary.by_severity.get(sev, 0)
            if count > 0:
                emoji = self._get_severity_emoji(sev)
                lines.append(f"| {emoji} {sev.capitalize()} | {count} |")

        lines.append("")
        lines.append("### Summary by Type")
        lines.append("| Type | Count |")
        lines.append("|------|-------|")
        for type_name, count in review.summary.by_type.items():
            if count > 0:
                lines.append(f"| {type_name.replace('_', ' ').title()} | {count} |")

        lines.append("")
        lines.append("### Issues Found")

        if not review.issues:
            lines.append("✅ No issues found!")
        else:
            grouped = self._group_by_type(review.issues)
            for type_name, issues in grouped.items():
                lines.append(f"#### {type_name.replace('_', ' ').title()} ({len(issues)})")
                lines.append("")

                for issue in issues:
                    emoji = self._get_severity_emoji(issue.severity.value)
                    lines.append(f"{emoji} **Line {issue.line_number}** [{issue.severity.value.upper()}]")
                    lines.append(f"> {issue.message}")
                    if issue.rule_id:
                        lines.append(f"> *Rule: `{issue.rule_id}`*")
                    if issue.suggestion:
                        lines.append(f"> 💡 **Suggestion:** {issue.suggestion}")
                    if issue.code_snippet:
                        lines.append(f"> ```python")
                        for line in issue.code_snippet.split('\n'):
                            lines.append(f"> {line}")
                        lines.append(f"> ```")
                    lines.append("")

        if review.ai_review:
            lines.append("---")
            lines.append("### 🤖 AI Review Summary")
            lines.append("")
            lines.append(review.ai_review)

        lines.append("")
        lines.append("---")
        lines.append("*Generated by AI Code Review Assistant*")

        return "\n".join(lines)

    def _group_by_type(self, issues: List[Issue]) -> dict:
        grouped = {}
        for issue in issues:
            type_name = issue.type.value
            if type_name not in grouped:
                grouped[type_name] = []
            grouped[type_name].append(issue)
        return grouped

    def _get_severity_emoji(self, severity: str) -> str:
        emojis = {
            "critical": "🔴",
            "high": "🟠",
            "medium": "🟡",
            "low": "🟢",
            "info": "🔵"
        }
        return emojis.get(severity, "⚪")

    def format_pr_summary_comment(self, reviews: List[ReviewResponse]) -> str:
        total_issues = sum(r.summary.total_issues for r in reviews)
        total_critical = sum(r.summary.by_severity.get("critical", 0) for r in reviews)
        total_high = sum(r.summary.by_severity.get("high", 0) for r in reviews)

        lines = [
            "## 🤖 AI Code Review - Pull Request Summary",
            "",
            f"**Files Reviewed:** {len(reviews)}",
            f"**Total Issues:** {total_issues}",
            f"**Critical:** {total_critical} | **High:** {total_high}",
            "",
        ]

        if total_critical > 0:
            lines.append("🚨 **BLOCKING:** Critical issues found - review required before merge")
        elif total_high > 0:
            lines.append("⚠️ **WARNING:** High severity issues found - review recommended")
        else:
            lines.append("✅ No blocking issues found")

        lines.append("")
        lines.append("### Per-File Summary")
        lines.append("| File | Issues | Critical | High | Medium | Low | Risk |")
        lines.append("|------|--------|----------|------|--------|-----|------|")

        for review in reviews:
            s = review.summary
            risk_emoji = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢", "none": "⚪"}.get(s.overall_risk, "⚪")
            lines.append(
                f"| {review.file_path} | {s.total_issues} | "
                f"{s.by_severity.get('critical', 0)} | "
                f"{s.by_severity.get('high', 0)} | "
                f"{s.by_severity.get('medium', 0)} | "
                f"{s.by_severity.get('low', 0)} | "
                f"{risk_emoji} {s.overall_risk} |"
            )

        return "\n".join(lines)